### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [nos86/vscphelper4python#2]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by grodansparadis** [comment]
Interesting case really. If the library is MIT can a binding be 
something else?

Den 2015-09-25 kl. 00:28, skrev Karan Goel:

> Without a license, this project isn't open source and no one can use the
> code.
> 
> Please use something like http://choosealicense.com/ to decide what
> license to use. I recommend MIT or GPL.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nos86/VSCP-Helper-for-Python/issues/2.

## 

Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by nos86** [comment]
Hi Karan,
I added MIT license on root folder; if it is enough, I'll close this issue.

Thanks for support,
Salvo
