### ISSUE TITLE
Extending

### ISSUE THREAD

**Issue by grodansparadis** [nos86/vscphelper4python#3]
Are you planning to extend this to include all methods in the helper lib?

**Comment by nos86** [comment]
Basically yes..
I'm working on it giving priority on all I need to start-up my home automation.
Now, I'm working on a DecisionMatrix decoding (for remote node) and DecisionMatrix "executable" (for virtual node based on this python module).

At this time, I have an overlap with other project, so I can't fix a milestone for release.

**Comment by grodansparadis** [comment]
Sounds great!  Many got interested in your project.

**Comment by nos86** [comment]
Good to hear
